# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 50a760faa80b631428eb47c3da5e07862f7bbe195d20d63f02e6a31804f64d5cb48c31a0eed8678f18a2638652113a25ac04785a269fb14888a4a483cdc50fed

test:
  secret_key_base: 17973b86a0ba13a591f3fa4727c242ecce66bb38c61168b48deaf75e9592aa79573fd80d8fbc4b7934d1792801c17e7797fa781c93e9c961c8eb32388b3928d1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
